services:
  typesense:
    build: .
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
      - .:/app
    env_file:
      - .env
    networks:
      global-net:

networks:
  global-net:
    external: true